# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rater_id',
            new_name='rater',
        ),
    ]
