# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:40
from __future__ import unicode_literals
import csv
from django.db import migrations
from ratings.models import Rating, Movie, Rater


def import_ratings(apps, schema_editor):
    with open('ratings/data/ratings.csv', encoding='latin-1') as f:
        ratings = csv.reader(f, delimiter="\t")
        for row in ratings:
            rater = Rater.objects.get(id=row[0])
            movie = Movie.objects.get(id=row[1])
            rating = Rating(rater=rater, movie=movie, score=row[2])
            rating.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20160505_2001'),
    ]

    operations = [
        migrations.RunPython(import_ratings),
    ]
