# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20160505_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='rater',
            name='occupation',
            field=models.CharField(default='Not given', max_length=200),
        ),
        migrations.AlterField(
            model_name='rater',
            name='sex',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
