# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_auto_20160507_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
