# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_auto_20160507_2051'),
        ('ratings', '0010_merge'),
    ]

    operations = [
    ]
