# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 22:09
from __future__ import unicode_literals

from django.db import migrations
from ratings.models import Rating, Movie


def del_unknown(apps, schema_editor):
    Rating.objects.filter(movie_id=267).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_merge'),
    ]

    operations = [
        migrations.RunPython(del_unknown),
    ]
