# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0013_auto_20160507_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
