# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0014_rater_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
