# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0015_rater_total_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movie_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
