# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 18:54
from __future__ import unicode_literals
from ratings.models import Rater
from django.contrib.auth.models import User
from django.db import migrations


def create_users(apps, schema_editor):
    raters = Rater.objects.all()
    for rater in raters:
        user = User.objects.create_user(id=rater.id,
                                        username='user_' + str(rater.id),
                                        password='password' + str(rater.id))
        rater.user = user
        rater.save()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0017_rater_user'),
    ]

    operations = [
        migrations.RunPython(create_users)
    ]
