# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0018_auto_20160509_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='rater',
            name='occupation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rater',
            name='sex',
            field=models.CharField(default='', max_length=200),
        ),
    ]
